#
# CMake platform file for PS3 PPC processor
#

cmake_minimum_required(VERSION 3.0...3.12)

include(${CMAKE_CURRENT_LIST_DIR}/ps3dev.cmake)

string(JOIN " " PPC_CFLAGS_STR ${PPC_CFLAGS})
string(JOIN " " PPC_LDFLAGS_STR ${PPC_LDFLAGS})
string(JOIN " " PPC_LIBS_STR ${PPC_LIBS})
list(TRANSFORM PPC_INC PREPEND "-I" OUTPUT_VARIABLE PPC_INC_FLAGS)
string(JOIN " " PPC_INC_STR ${PPC_INC_FLAGS})
list(TRANSFORM PPC_LIB PREPEND "-I" OUTPUT_VARIABLE PPC_LIB_FLAGS)
string(JOIN " " PPC_LIB_STR ${PPC_LIB_FLAGS})

set(CMAKE_C_FLAGS_INIT "${PPC_CFLAGS_STR} ${PPC_INC_STR}")
set(CMAKE_CXX_FLAGS_INIT ${CMAKE_C_FLAGS_INIT})
set(CMAKE_EXE_LINKER_FLAGS_INIT ${CMAKE_EXE_LINKER_FLAGS_INIT} "${PPC_LDFLAGS_STR} ${PPC_LIB_STR}")
set(CMAKE_SHARED_LINKER_FLAGS ${CMAKE_SHARED_LINKER_FLAGS} "${PPC_LIBS_STR}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_INSTALL_PREFIX "$ENV{PS3DEV}/portlibs/ppu" CACHE PATH "" FORCE)
set(CMAKE_PREFIX_PATH "$ENV{PS3DEV}/portlibs/ppu" CACHE PATH "" FORCE)

add_definitions(-DPS3)
set(PS3                 TRUE)

# SDL3
set(SDL_TESTS          FALSE)
set(SDL_EXAMPLES       FALSE)
set(SDL_TEST_LIBRARY   FALSE)
set(SDL_STATIC            ON)
set(SDL_GPU              OFF)
set(SDL_CAMERA           OFF)
set(SDL_HAPTIC           OFF)
set(SDL_HIDAPI           OFF)
set(SDL_POWER            OFF)
set(SDL_SENSOR           OFF)
set(SDL_DIALOG           OFF)
set(SDL_DISKAUDIO        OFF)
set(SDL_DUMMYAUDIO       OFF)
set(SDL_DUMMYCAMERA      OFF)
set(SDL_DUMMYVIDEO       OFF)
set(SDL_OFFSCREEN        OFF)
set(SDL_RENDER_GPU       OFF)
set(SDL_TRAY             OFF)
set(SDL_VIRTUAL_JOYSTICK OFF)

# SDL3_mixer
set(BUILD_SHARED_LIBS          OFF)
set(SDLMIXER_TESTS             OFF)
set(SDLMIXER_TESTS_INSTALL     OFF)
set(SDLMIXER_EXAMPLES          OFF)
set(SDLMIXER_OPUS              OFF)
set(SDLMIXER_VORBIS_VORBISFILE OFF)
set(SDLMIXER_WAVPACK           OFF)
set(SDLMIXER_FLAC              OFF)
set(SDLMIXER_MP3_MPG123        OFF)
set(SDLMIXER_GME               OFF)
set(SDLMIXER_MIDI_TIMIDITY     OFF)

# SDL3_ttf
set(SDLTTF_VENDORED             ON)
set(SDLTTF_HARFBUZZ            OFF)
set(SDLTTF_SAMPLES             OFF)
