name: Build libraries package

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_ps3libraries:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set env vars
      id: slug
      run: |
        echo "sha_name=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
        sudo apt-get -y install autoconf automake bison flex make texinfo patch wget zlib1g-dev libtool-bin bzip2 pkg-config

      # using pre-compiled PS3 toolchain
    - name: Download PSL1GHT Toolchain
      run: |
        curl -sL https://github.com/ps3dev/ps3toolchain/releases/download/2026-06-09/ps3dev-92534e60-ubuntu-latest.tar.gz | tar xvz -C ./
        echo "PS3DEV=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV
        echo "PSL1GHT=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV

    - name: Install libraries
      run: |
        sed -i.bak '8d' libraries-sudo.sh
        ./libraries-sudo.sh

    - name: Build Package
      run: |
        7z a ps3libraries.zip $PSL1GHT/portlibs/

    - name: Push package artifact
      uses: actions/upload-artifact@v4
      with:
        name: ps3libraries-build_${{ env.sha_name }}
        path: ps3libraries.zip
        if-no-files-found: error
